export const data = [
	{label: 'Calcium, Ca', quantity: 0.125, unit: 'mg'},
	{label: 'Carbohydrate, by difference', quantity: 12.5, unit: 'g'},
	{label: 'Carbohydrates (net)', quantity: 12.5, unit: 'g'},
	{label: 'Cholesterol', quantity: 0, unit: 'mg'},
	{label: 'Energy', quantity: 48.375, unit: 'kcal'},
	{label: 'Fatty acids, total monounsaturated', quantity: 0, unit: 'g'},
	{label: 'Fatty acids, total polyunsaturated', quantity: 0, unit: 'g'},
	{label: 'Fatty acids, total saturated', quantity: 0, unit: 'g'},
	{label: 'Total lipid (fat)', quantity: 0, unit: 'g'},
	{label: 'Iron, Fe', quantity: 0.00625, unit: 'mg'},
	{label: 'Fiber, total dietary', quantity: 0, unit: 'g'},
	{label: 'Folic acid', quantity: 0, unit: 'µg'},
	{label: 'Folate, DFE', quantity: 0, unit: 'µg'},
	{label: 'Folate, food', quantity: 0, unit: 'µg'},
	{label: 'Potassium, K', quantity: 0.25, unit: 'mg'},
	{label: 'Magnesium, Mg', quantity: 0, unit: 'mg'},
	{label: 'Sodium, Na', quantity: 0.125, unit: 'mg'},
	{label: 'Niacin', quantity: 0, unit: 'mg'},
	{label: 'Phosphorus, P', quantity: 0, unit: 'mg'},
	{label: 'Protein', quantity: 0, unit: 'g'},
	{label: 'Riboflavin', quantity: 0.002375, unit: 'mg'},
	{label: 'Sugars, total including NLEA', quantity: 12.475, unit: 'g'},
	{label: 'Sugars, added', quantity: 12.475, unit: 'g'},
	{label: 'Thiamin', quantity: 0, unit: 'mg'},
	{label: 'Vitamin E (alpha-tocopherol)', quantity: 0, unit: 'mg'},
	{label: 'Vitamin A, RAE', quantity: 0, unit: 'µg'},
	{label: 'Vitamin B-6', quantity: 0, unit: 'mg'},
	{label: 'Vitamin B-12', quantity: 0, unit: 'µg'},
	{label: 'Vitamin C, total ascorbic acid', quantity: 0, unit: 'mg'},
	{label: 'Vitamin D (D2 + D3)', quantity: 0, unit: 'µg'},
	{label: 'Vitamin K (phylloquinone)', quantity: 0, unit: 'µg'},
	{label: 'Water', quantity: 0.0025, unit: 'g'},
	{label: 'Zinc, Zn', quantity: 0.00125, unit: 'mg'}
]